### PR TITLE
add two liftover pipline and update region extraction

### PR DESCRIPTION
**Pull request by changebio**

### CODE REVIEW

**Comment by gaow** [comment]
@changebio please let me know when i should review and merge. Thank you!

**Comment by changebio** [comment]
Yes, please. @gaow

**Comment by gaow** [comment]
@changebio @dianacornejo was complaining about bgen read file issue with the new code. Is that fixed in this patch?

**Comment by changebio** [comment]
> @changebio @dianacornejo was complaining about bgen read file issue with the new code. Is that fixed in this patch?

The issue has been fixed in the newest version. I added both been-reader and pybgen to read been files. I tested on MWE and @dianacornejo is testing on whole chromosome data.

**Pull request merged**
