### PR TITLE
LMM manhatthan change

### PR DESCRIPTION
**Pull request by dianacornejo**
@gaow I don't know why the region extraction is changing...but I compared to the version on github and they same to be exactly the same

### CODE REVIEW

**Comment by gaow** [comment]
@dianacornejo region extract codes are not the same. Please review this for the difference and make sure this is what you want:

https://github.com/cumc/bioworkflows/pull/125/files

**Comment by dianacornejo** [comment]
@gaow I just want to keep whatever changes Yin made to the Region_extraction...so let me modify that

**Comment by dianacornejo** [comment]
@gaow I fixed it now. Thank you

**Comment by gaow** [comment]
@changebio could you review the patch and communicate offline with @dianacornejo to make sure everything is in order? I would like to avoid any unintentional changes to other's codes that I'm less familar with.

**Comment by gaow** [comment]
@changebio let's just check if https://github.com/cumc/bioworkflows/blob/master/GWAS/RegionExtraction_LDmatrix.ipynb is the correct version. 

I believe later we 'll modify it to use the new summary stats merger codes you have?

**Pull request merged**
