### PR TITLE
Fixed PCA plot problem

### PR DESCRIPTION
**Pull request by UxxUnet**

### CODE REVIEW

**Comment by gaow** [comment]
@UxxUnet still am curious why would you need `as.double`? what does it use without `as.double`? A string? It should not be the case at least from the code. I"m wondering what might be going on.

**Comment by dianacornejo** [comment]
If we do not use as double the variable is left empty, even if it defaults to the first part of the code and it complains about a parsing error as shown in the images. 

image
image (1)

**Comment by UxxUnet** [comment]
> @UxxUnet still am curious why would you need `as.double`? what does it use without `as.double`? A string? It should not be the case at least from the code. I"m wondering what might be going on.

Sorry, I have a detailed record here.

[https://github.com/UxxUnet/bioworkflows/blob/master/prototype/PCA_plot_problem.ipynb](https://github.com/UxxUnet/bioworkflows/blob/master/prototype/PCA_plot_problem.ipynb)

**Comment by gaow** [comment]
@UxxUnet @dianacornejo ahh i get it now. Yeah parsing error ... i should have thought of that. Thank you both this is execellent!!

**Pull request merged**
